# Generated by Django 5.0.6 on 2024-06-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='image_url',
            field=models.URLField(default='', max_length=2083),
            preserve_default=False,
        ),
    ]
